### PR TITLE
Fix: Ordering and displaying icons in closed market

### LINKED ISSUE #161: When markets are closed, show the correct answer
image

Can be with a checkmark or somthing similar to show those are correct answers.
For categorical show one answer. For Multicategorical it can show more than one.
For scalar nothing to show.

### PR DESCRIPTION
**Pull request by shan-pt**
Fixes #161
Screenshot 2024-12-03 060903

### CODE REVIEW

File: web/src/components/Market/Header/MarketHeader.tsx [hunk 1]
```diff
@@ -62,13 +78,63 @@ function OutcomesInfo({
     isFetching,
   } = useMarketOdds(market, isIntersecting, isOgImage);
 
+  const routerAddress = getRouterAddress(market.chainId);
+
+  const winningOutcomes = useQuery({
```
Comment (xyzseer) [inline web/src/components/Market/Header/MarketHeader.tsx:83]: move this to a hook file `hooks/useWinningOutcomes.tsx`

File: web/src/components/Market/Outcomes.tsx [hunk 2]
```diff
@@ -202,13 +215,57 @@ export function Outcomes({ market, images }: PositionsProps) {
   const { Modal, openModal, closeModal } = useModal("liquidity-modal");
   const blockExplorerUrl = SUPPORTED_CHAINS[market.chainId].blockExplorers?.default?.url;
 
+  const routerAddress = getRouterAddress(market.chainId);
+  const { data: marketStatus } = useMarketStatus(market);
+  const winningOutcomes = useQuery({
```
Comment (xyzseer) [inline web/src/components/Market/Outcomes.tsx:220]: this hook is duplicated, it should use the new `useWinningOutcomes` hook too

File: web/src/components/Market/Outcomes.tsx [hunk 3]
```diff
@@ -202,13 +215,57 @@ export function Outcomes({ market, images }: PositionsProps) {
...
+  });
+
   const indexesOrderedByOdds = useMemo(() => {
     if (oddsPending || odds.length === 0) {
       return null;
     }
-    const oddsAndIndexes = odds.map((odd, i) => ({ odd, i })).sort((a, b) => b.odd - a.odd);
-    return oddsAndIndexes.map((obj) => obj.i);
-  }, [odds]);
+    const invalidIndex = market.outcomes.findIndex(outcome => outcome === INVALID_RESULT_OUTCOME_TEXT);
```
Comment (xyzseer) [inline web/src/components/Market/Outcomes.tsx:238]: the code inside the useMemo seems to be duplicated on both files, the OutcomeWithOdds type definition too. Let's move all of this to a function to allow to reuse it everywhere it's needed (maybe it can even be a react query hook, your choice :))
